name: Python application

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        target: [x86_64]
    defaults:
      run:
        working-directory: ./src/python
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run tests
        run: |
          pip install pytest
          pytest
